
export const DOM = {
    loginScreen: document.getElementById('login-screen'),
    dashboardScreen: document.getElementById('dashboard-screen'),
    loginForm: document.getElementById('login-form'),
    loginError: document.getElementById('login-error'),
    userEmailDisplay: document.getElementById('user-email'),
    btnLogout: document.getElementById('btn-logout'),
    clientsUl: document.getElementById('clients-ul'),
    btnNewClient: document.getElementById('btn-new-client'),
    clientManager: document.getElementById('client-manager'),
    managerTitle: document.getElementById('manager-title'),
    clientStatus: document.getElementById('client-status'),
    storeStatus: document.getElementById('store-status'),
    clientWhatsapp: document.getElementById('client-whatsapp'),
    btnSaveWhatsapp: document.getElementById('btn-save-whatsapp'),
    clientInstagram: document.getElementById('client-instagram'),
    btnSaveInstagram: document.getElementById('btn-save-instagram'),
    clientUrl: document.getElementById('client-url'),
    btnSaveUrl: document.getElementById('btn-save-url'),
    clientLink: document.getElementById('client-link'),
    productsTbody: document.getElementById('products-tbody'),
    btnAddProduct: document.getElementById('btn-add-product'),
    btnDeleteClient: document.getElementById('btn-delete-client'),
    inputPlan: document.getElementById('client-plan'),
    inputCedula: document.getElementById('client-cedula'),
    inputDeuda: document.getElementById('client-deuda'),
    inputVencimiento: document.getElementById('client-vencimiento'),
    btnSaveBilling: document.getElementById('btn-save-billing'),
    colorPicker: document.getElementById('client-color-picker'),
    colorHex: document.getElementById('client-color-hex'),
    btnVisitUrl: document.getElementById('btn-visit-url'),
    btnSaveConfig: document.getElementById('btn-save-config'),
    btnGenerateQr: document.getElementById('btn-generate-qr'),
    qrModal: document.getElementById('qr-modal'),
    btnCloseQr: document.getElementById('btn-close-qr'),
    btnDownloadQr: document.getElementById('btn-download-qr'),
    qrContainer: document.getElementById('qr-code-container'),
    qrUrlText: document.getElementById('qr-url-text'),
    billingStatusIndicator: document.getElementById('billing-status-indicator'),
    promosTbody: document.getElementById('promos-tbody'),
    btnAddPromo: document.getElementById('btn-add-promo'),
    btnImportBulk: document.getElementById('btn-import-bulk'),
    importModal: document.getElementById('import-modal'),
    btnConfirmImport: document.getElementById('btn-confirm-import'),
    btnCancelImport: document.getElementById('btn-cancel-import'),
    importRawText: document.getElementById('import-raw-text'),
    geminiApiKey: document.getElementById('gemini-api-key'),
    aiLoadingText: document.getElementById('ai-loading-text')
};

export const state = {
    currentClientId: null,
    clientsData: {},
    currentClientData: null
};
